apiVersion: apps/v1
kind: Deployment
metadata:
  name: ygfds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ygfds
  template:
    metadata:
      labels:
        app: ygfds
    spec:
      containers:
      - image: okteto.dev/ygfds:latest
        name: ygfds
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "66ebac31-fe31-43cf-bdb0-014d18cf3b73"
        - name: Vless_Path
          value: "/vl789"
        - name: Vmess_UUID
          value: "66ebac31-fe31-43cf-bdb0-014d18cf3b73"
        - name: Vmess_Path
          value: "/vm456"
        - name: Share_Path
          value: "/v2link"
